driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
- name: default
  run_list: xfs::default
- name: dev_pkgs
  run_list: xfs::default
  attributes:
    xfs:
      dev_packages: true
