AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
#
# we like our neatly-aligned code too much
#
SingleSpaceBeforeFirstArg:
  Enabled: false
